serials:
  family: 710
  loan: 200
  officesupply: 920
  partnercompany: 300
  insurance: 100
  accidentHistory: 410
  accident: 400
  additionalAllowance:
  automobile:
  benefit:
  collateral:
  compensationDetail:
  complaint: 510
  contract: 100
  counsel: 520
  customer: 200
  department: 910
  depositDetail: 810
  diseaseHistory: 510
  employee: 600
