serials:
  accident: 400
  accidentHistory: 410
  compensationDetail: 930
  complaint: 510
  contract: 100
  counsel: 520
  customer: 200
  department: 910
  depositDetail: 810
  diseaseHistory: 510
  employee: 600
  family: 710
  insurance: 100
  insuranceMoney: 110
  loan: 200
  officesupply: 920
  paymentDetail: 900
  partnercompany: 300
  product: 700
  report: 500
  surgeryHistory: 610