spring:
  application:
    name: BunsanedThinking_SpringBack
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bunsaninsurance
    username: root
    password: Godyell713!
  profiles:
    include: serials
  config:
    import:
      - classpath:constants/application-serials.yaml
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
