spring:
  application:
    name: BunsanedThinking_SpringBack
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bunsaninsurance
    username: root
    password: 29499805
  profiles:
    include: serials
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
