spring:
  application:
    name: BunsanedThinking_SpringBack
  profiles:
    include: serials, secret
  config:
    import:
      - classpath:/constants/application-serials.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
